### ISSUE TITLE
problem when trying to remove about or home folders

### ISSUE THREAD

**Issue by samehelhawary** [archfirst/angular2-seed-sass#11]
I want to start from scratch, when I try to delete home or about folder from src they are reproduced again? is this a feature or a bug and how to stop them from reproduced every time I remove them?

**Comment by asgarddesigns** [comment]
They shouldn't be re-added unless you are deleting from the dist folder... make sure you are deleting from /src/

**Comment by nareshbhatia** [comment]
I agree with @asgarddesigns. Deleting `home` and `about` folders from src should in fact break the build because they are referenced from app.component.ts:

```
src/app/components/app.component.ts (5,29): Cannot find module '../../home/components/home.component'. (2307)
src/app/components/app.component.ts (6,30): Cannot find module '../../about/components/about.component'. (2307)
```

Please make sure you are indeed deleting them from src and not from dist. If you are still experiencing the problem, you can reopen this issue.
