### ISSUE TITLE
App not working when upgrading from angular beta to angular rc-1

### ISSUE THREAD

**Issue by vdest** [archfirst/angular2-seed-sass#19]
Are there any special requirements for this kind of upgrade? Is the problem related to npm package (angular is now distributed as @angular)?

**Comment by nareshbhatia** [comment]
@vdest, the rc-1 release has several changes that are incompatible with the beta releases. I have decided not to upgrade angular2-seed-sass to rc-1, because I have personally switched to [angular-cli](https://github.com/angular/angular-cli). While it is still in beta, the tool has the official support from the Angular team and has the best minds working on it. I would highly recommend that you switch over too and help the angular-cli team make that tool better.
