### ISSUE TITLE
npm test fails because of missing css

### ISSUE THREAD

**Issue by perrywoodin** [archfirst/angular2-seed-sass#8]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**
`npm test`

_What steps should we try in your demo to see the problem?_

**Current behavior**
End up with an error like:
WARN [web-server]: 404: /base/dist/dev/home/components/home.component.js

**Expected/desired behavior**

**Other information**
If you change the Component styleURLs from:
`styleUrls: ['./home.component.css']`

to:
`styleUrls: ['./home.component.scss']`

The tests pass.

**Comment by asgarddesigns** [comment]
Cheers @perrywoodin , had a quick look and need to dig into the config to process scss files with karma tests. Renaming to scss creates other problems and is probably not the correct solution, will try and look into this over the next few days.

**Comment by joshwiens** [comment]
@perrywoodin @asgarddesigns - For reference, this has nothing to do with Karma.

If you look at build.js.test.ts it inlines the templates on a test run.

With the current project implementation, all of the component styles are set to look for css which doesn't exist until the process.scss task is executed.

That said, until gulp-inline-ng2-template ludohenin/gulp-inline-ng2-template#28 supports variable resolution there isn't a whole lot you can do about it as the test build is "technically" going to fail anyway.

**Comment by asgarddesigns** [comment]
@d3viant0ne Yep, I'm in the same position and trying to find a way around it. My plan was to preprocess the sass files into css but not had much luck.

Failing that, removing inlining may be the temporary fix, does gulp-inline-ng2-template confer a big speed benefit? I am guessing it's probably very nice to have with the larger projects...

**Comment by nareshbhatia** [comment]
The test build should work exactly like the dev build - it should not do inlining of templates or CSS. Inlining is for prod builds only where we need to package up the components. Based on this, I have removed inlining from the test build. This allows the process to push forward, but it is now failing at run time. The components are not able to load the templates. I can't figure this one out, because the templates do exist where the component is looking for them!!! See the error message below:

```
  About component
    ✖ should work
      Chrome 49.0.2623 (Mac OS X 10.11.4)
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
    Failed: Failed to load /Users/nbhati/projects/angular2-seed-sass/dist/dev/about/components/about.component.html
    invoke@/Users/nbhati/projects/angular2-seed-sass/node_modules/zone.js/dist/zone.js:308:34
    run@/Users/nbhati/projects/angular2-seed-sass/node_modules/zone.js/dist/zone.js:201:50
    /Users/nbhati/projects/angular2-seed-sass/node_modules/zone.js/dist/zone.js:553:61
    invokeTask@/Users/nbhati/projects/angular2-seed-sass/node_modules/zone.js/dist/zone.js:341:43
    runTask@/Users/nbhati/projects/angular2-seed-sass/node_modules/zone.js/dist/zone.js:238:58
    drainMicroTaskQueue@/Users/nbhati/projects/angular2-seed-sass/node_modules/zone.js/dist/zone.js:459:43
```

The message above says failed to load `about.component.html`. I don't understand why - the file does exist at that location. Any ideas?

**Comment by joshwiens** [comment]
@nareshbhatia - I tried to get this to work properly for almost a week and eventually gave up.

If you step deep into zone, it's looking for it where it where it isn't ( path issue ). So while it's technically a bug, it's going to get stuffed in a back log somewhere because I'm sure SASS / SCSS support for inline templates isn't in the 1.0 scope.

My solution to this was a postcss implementation that as a side-effect decreased by build/re-build times quite a bit. So call it 90% of the Sass functionality I wanted with none of the b.s. trying to get this to work properly.

**Comment by nareshbhatia** [comment]
Hmmm, interesting! Can you please clarify why it is a SASS / SCSS support issue? The way the test process is set up, there is no SASS involved at runtime - the compiled JS file looks like this:

```
AboutComponent = __decorate([
    core_1.Component({
        selector: 'sd-about',
        moduleId: module.id,
        templateUrl: './about.component.html',
        styleUrls: ['./about.component.css']
    }), 
```

At runtime `about.component.html` and `about.component.css` are available in the same folder. So I can't understand why they can't be loaded. This is the exact same setup during the dev build and there are no issues there.

**Comment by amaltsev** [comment]
It took me a while to trace it, but I think in the end the solution is just a two-line change in karma config. I attached a pull request.

**Comment by nareshbhatia** [comment]
Awesome work, @amaltsev! Merged.

Thanks.

**Comment by joshwiens** [comment]
Wow, talk about looking in the wrong place. Seed : 1, Josh : 0. @amaltsev Nice job running that down.
